# Generated by Django 6.0.2 on 2026-03-31 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0004_project_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='projectrating',
            options={'verbose_name': 'Project Rating', 'verbose_name_plural': 'Project Ratings'},
        ),
        migrations.AlterModelOptions(
            name='projectreview',
            options={'verbose_name': 'Project Review', 'verbose_name_plural': 'Project Reviews'},
        ),
    ]
