# Generated by Django 6.0.2 on 2026-04-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0005_alter_favorite_id_alter_project_id_and_more'),
        ('diyprojects', '0005_alter_project_options_alter_favorite_id_and_more'),
    ]

    operations = [
    ]
