# Generated by Django 6.0.2 on 2026-03-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0005_alter_favorite_options_alter_projectrating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('To-Do', 'To-Do'), ('Done', 'Done')], default='Backlog'),
        ),
    ]
