# Generated by Django 6.0.2 on 2026-03-31 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0006_alter_favorite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='diyprojects.project'),
        ),
    ]
