# Generated by Django 6.0.2 on 2026-05-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0006_merge_20260430_2152'),
        ('diyprojects', '0007_projectreview_parent_reviewvote'),
    ]

    operations = [
    ]
