# Generated by Django 6.0.2 on 2026-05-06 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0008_merge_20260501_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrating',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
