# Generated by Django 6.0.2 on 2026-03-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0008_projectrating_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrating',
            name='project',
        ),
    ]
