# Generated by Django 6.0.2 on 2026-03-31 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0009_remove_projectrating_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrating',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='diyprojects.project'),
        ),
    ]
