# Generated by Django 6.0.2 on 2026-05-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0009_alter_favorite_id_alter_project_id_and_more'),
        ('diyprojects', '0009_alter_projectrating_score'),
    ]

    operations = [
    ]
