# Generated by Django 6.0.2 on 2026-03-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('diyprojects', '0010_projectrating_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectrating',
            unique_together={('project', 'profile')},
        ),
    ]
