# Generated by Django 6.0.2 on 2026-05-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0011_alter_favorite_id_alter_project_id_and_more'),
        ('diyprojects', '0011_merge_20260507_1548'),
    ]

    operations = [
    ]
