# Generated by Django 6.0.2 on 2026-04-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0011_alter_projectrating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diyprojects_images/'),
        ),
    ]
