# Generated by Django 4.2.30 on 2026-04-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Market Seller', 'Market Seller'), ('Event Organizer', 'Event Organizer'), ('Customer', 'Customer'), ('Book Contributor', 'Book Contributor')], default='Customer', max_length=50),
        ),
    ]
