# Generated by Django 6.0.2 on 2026-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Market Seller', 'Market Seller'), ('Event Organizer', 'Event Organizer'), ('Customer', 'Customer'), ('Commission Maker', 'Commission Maker')], default='Customer', max_length=50),
        ),
    ]
