# Generated by Django 6.0.2 on 2026-04-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_id_alter_profile_role'),
        ('accounts', '0006_alter_profile_id'),
    ]

    operations = [
    ]
