# Generated by Django 6.0.2 on 2026-04-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_id_alter_profile_role'),
        ('accounts', '0007_merge_20260430_1641'),
    ]

    operations = [
    ]
