# Generated by Django 6.0.2 on 2026-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20260501_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Market Seller', 'Market Seller'), ('Event Organizer', 'Event Organizer'), ('Customer', 'Customer'), ('Commission Maker', 'Commission Maker'), ('Project Creator', 'Project Creator'), ('Book Contributor', 'Book Contributor')], default='Customer', max_length=50),
        ),
    ]
