# Generated by Django 6.0.2 on 2026-05-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20260430_2152'),
        ('accounts', '0009_alter_profile_role'),
    ]

    operations = [
    ]
