# Generated by Django 6.0.2 on 2026-04-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0005_alter_product_id_alter_producttype_id'),
        ('merchstore', '0005_product_owner_product_product_image_product_status_and_more'),
    ]

    operations = [
    ]
