<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-04-30 01:50
=======
# Generated by Django 6.0.2 on 2026-04-21 15:33
>>>>>>> 252b6fefaa108edc52a660a8d57a07e5575e285e

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('bookclub', '0004_alter_book_id_alter_genre_id'),
=======
    dependencies = [
        ("bookclub", "0004_alter_book_id_alter_genre_id"),
>>>>>>> 252b6fefaa108edc52a660a8d57a07e5575e285e
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
=======
            model_name="book",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
>>>>>>> 252b6fefaa108edc52a660a8d57a07e5575e285e
        ),
    ]
