# Generated by Django 6.0.2 on 2026-04-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_alter_book_options_alter_genre_options_and_more'),
        ('bookclub', '0005_alter_book_id_alter_genre_id'),
    ]

    operations = [
    ]
