# Generated by Django 6.0.2 on 2026-05-01 07:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_role'),
        ('bookclub', '0007_alter_book_id_alter_bookmark_id_alter_bookreview_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='bookclub.book'),
        ),
        migrations.AddConstraint(
            model_name='bookreview',
            constraint=models.UniqueConstraint(fields=('user_reviewer', 'book'), name='one_review_per_user_per_book'),
        ),
    ]
