# Generated by Django 6.0.2 on 2026-05-01 11:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_role'),
        ('bookclub', '0008_bookreview_rating_alter_bookmark_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='bookreview',
            name='one_review_per_user_per_book',
        ),
        migrations.AddField(
            model_name='bookrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='bookclub.book'),
        ),
        migrations.AddField(
            model_name='bookrating',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to='accounts.profile'),
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='rating',
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('book', 'profile')},
        ),
    ]
