# Generated by Django 6.0.2 on 2026-02-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commission_commission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
