# Generated by Django 6.0.2 on 2026-02-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_commission_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='commission_type',
            new_name='type',
        ),
    ]
