# Generated by Django 6.0.2 on 2026-03-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_rename_commission_type_commission_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='commissiontype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='commission',
            name='people_required',
            field=models.PositiveIntegerField(),
        ),
    ]
