# Generated by Django 6.0.2 on 2026-04-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0003_event_event_capacity_event_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
