# Generated by Django 6.0.2 on 2026-04-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0003_event_event_capacity_event_event_image_and_more'),
        ('localevents', '0004_alter_event_id_alter_eventtype_id'),
    ]

    operations = [
    ]
