<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-04-30 01:50
=======
# Generated by Django 6.0.2 on 2026-04-26 15:30
>>>>>>> 252b6fefaa108edc52a660a8d57a07e5575e285e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0004_alter_event_id_alter_eventtype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
