# Generated by Django 6.0.2 on 2026-04-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_id'),
        ('localevents', '0006_alter_event_id_alter_eventsignup_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='user_registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='eventsignup',
            unique_together={('event', 'user_registrant')},
        ),
    ]
