# Generated by Django 6.0.2 on 2026-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0007_alter_eventsignup_user_registrant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='new_registrant',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
