# Generated by Django 6.0.2 on 2026-04-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0005_alter_event_id_alter_eventtype_id'),
        ('localevents', '0008_alter_eventsignup_new_registrant'),
    ]

    operations = [
    ]
