# Generated by Django 6.0.2 on 2026-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_role'),
        ('localevents', '0009_merge_20260430_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(related_name='organizers', to='accounts.profile'),
        ),
    ]
